login_and_register
IrenaKozlovskaya/ProgectSchoolOrganizer pull request #1
Opened 2021-07-24 00:47 UTC by IrenaKozlovskaya

Вход и регистрация готовы. Надеюсь с большего все правильно)Подскажите если что можно улучшить или исправить!

2021-07-25 12:16 UTC, RomanKashenok requested changes
давай чуток подправим :)

2021-07-25 12:16 UTC, RomanKashenok commented on SchoolOrganizer/pom.xml
> +    </dependency>
убирай отсюда плагин

2021-07-25 12:16 UTC, RomanKashenok commented on SchoolOrganizer/src/main/java/com/myapp/config/WebConfig.java
> +        System.out.println("WebMvcConfigurer - addResourceHandlers() function get loaded...");
убирай консольные выводы

2021-07-25 12:16 UTC, RomanKashenok commented on SchoolOrganizer/src/main/java/com/myapp/controller/UserController.java
> +            for (User u : users) {
а давай мы не будем доставать всех пользователей и перебирать их, а просто попробуем найти одного с таким email'ом, который хотят зарегистрировать

2021-07-25 12:16 UTC, RomanKashenok commented on SchoolOrganizer/src/main/java/com/myapp/controller/UserController.java
> +            for (User u : users) {
то же самое :)

2021-07-25 12:16 UTC, RomanKashenok commented on SchoolOrganizer/src/main/java/com/myapp/model/User.java
> +    public String toString() {
если уж используем lombok, то давай и @ToString использовать )

2021-07-25 12:16 UTC, RomanKashenok commented on SchoolOrganizer/src/main/java/com/myapp/repository/impl/UserDaoImpl.java
> +        String sql = "INSERT INTO users(email, password) values (?, ?)";
двавй все запросы в константы класса вынесем )

2021-08-02 15:56 UTC, IrenaKozlovskaya commented on SchoolOrganizer/pom.xml
> +    </dependency>
убрала

2021-08-02 15:56 UTC, IrenaKozlovskaya commented on SchoolOrganizer/src/main/java/com/myapp/config/WebConfig.java
> +        System.out.println("WebMvcConfigurer - addResourceHandlers() function get loaded...");
убрала

2021-08-02 15:57 UTC, IrenaKozlovskaya commented on SchoolOrganizer/src/main/java/com/myapp/controller/UserController.java
> +            for (User u : users) {
исправлено!

2021-08-02 15:58 UTC, IrenaKozlovskaya commented on SchoolOrganizer/src/main/java/com/myapp/model/User.java
> +    public String toString() {
не знала про to string, да уж))

2021-08-02 15:58 UTC, IrenaKozlovskaya commented on SchoolOrganizer/src/main/java/com/myapp/repository/impl/UserDaoImpl.java
> +        String sql = "INSERT INTO users(email, password) values (?, ?)";
вынесла

2021-08-03 20:12 UTC, RomanKashenok approved these changes
Роль только вынеси отдельно, а не строкой в User.java

2021-08-03 20:12 UTC, RomanKashenok commented on SchoolOrganizer/src/main/java/com/myapp/model/User.java
> +    private String role;
роль правильно делать отдельной сущностью

2021-08-06 20:38 UTC, IrenaKozlovskaya commented on SchoolOrganizer/src/main/java/com/myapp/model/User.java
> +    private String role;
изменила

2021-08-07 16:28 UTC, RomanKashenok approved these changes

2021-08-09 11:39 UTC, merged