security
IrenaKozlovskaya/ProgectSchoolOrganizer pull request #3
Opened 2021-08-09 14:20 UTC by IrenaKozlovskaya

Security are ready and works)

2021-08-09 19:29 UTC, RomanKashenok requested changes

2021-08-09 19:29 UTC, RomanKashenok commented on SchoolOrganizer/src/main/java/com/myapp/security/UserAuthenticationProvider.java
> +        if (user == null || !user.getEmail().equalsIgnoreCase(email)) {
!user.getEmail().equalsIgnoreCase(email)
оч странно сравнивать мэйл пользователя, взятый из пользователя с мэйлом пользователя, по которому ты этого пользователя и нашла.

2021-08-09 19:29 UTC, RomanKashenok commented on SchoolOrganizer/src/main/java/com/myapp/security/UserAuthenticationProvider.java
> +        if (email.equalsIgnoreCase(user.getEmail()) && password.equals(user.getPassword())) {
ты уже все условия на несовпадение проверила, зачем еще раз проверять на совпадение?

2021-08-09 19:29 UTC, RomanKashenok commented on SchoolOrganizer/src/main/java/com/myapp/repository/UserDao.java
> +    void setUpDefaultRole(Long id);
это наверное должно быть в RoleDao? Или как у тебя репозиторий, работающий с юзерами, создает еще какие-то роли?

2021-08-09 19:29 UTC, RomanKashenok commented on SchoolOrganizer/src/main/java/com/myapp/repository/impl/UserDaoImpl.java
> +    public void setUpDefaultRole(Long id) {
обращайся для этого к roleDao

2021-08-09 19:29 UTC, RomanKashenok commented on SchoolOrganizer/src/main/java/com/myapp/service/UserService.java
> +    void setUpDefaultUserRole(Long id);
замечания выше

2021-08-17 21:18 UTC, IrenaKozlovskaya commented on SchoolOrganizer/src/main/java/com/myapp/repository/UserDao.java
> +    void setUpDefaultRole(Long id);
перенесла в RoleDao)

2021-08-17 21:20 UTC, IrenaKozlovskaya commented on SchoolOrganizer/src/main/java/com/myapp/security/UserAuthenticationProvider.java
> +        if (user == null || !user.getEmail().equalsIgnoreCase(email)) {
и действительно...странно, зачем я это сделала)

2021-08-17 21:20 UTC, IrenaKozlovskaya commented on SchoolOrganizer/src/main/java/com/myapp/security/UserAuthenticationProvider.java
> +        if (email.equalsIgnoreCase(user.getEmail()) && password.equals(user.getPassword())) {
Спасибо! изменено

2021-08-26 08:13 UTC, RomanKashenok approved these changes

2021-09-02 14:56 UTC, merged